interface ProductsModelI {
  bar_code: string | null;
  categories_id: number | null;
  created_at: Date; // generated by db
  depth: number | null;
  description: string | null;
  fragile: number | null;
  heavy: number | null;
  height: number | null;
  name: string;
  products_id: number; // generated by db
  qr_code: string | null;
  quantity: number;
  refrigerated: number | null;
  sku_code: string | null;
  updated_at: Date; // generated by db
  weight: number | null;
  width: number | null;
}

class ProductsModel {
  readonly barCode: string;
  readonly categoriesId: number;
  readonly createdAt: Date;
  readonly depth: number;
  readonly description: string;
  readonly fragile: number;
  readonly heavy: number;
  readonly height: number;
  readonly name: string;
  readonly productsId: number;
  readonly qrCode: string;
  readonly quantity: number;
  readonly refrigerated: number;
  readonly skuCode: string;
  readonly updatedAt: Date;
  readonly weight: number;
  readonly width: number;

  constructor({
    bar_code,
    categories_id,
    created_at,
    depth,
    description,
    fragile,
    heavy,
    height,
    name,
    products_id,
    qr_code,
    quantity,
    refrigerated,
    sku_code,
    updated_at,
    weight,
    width,
  }: ProductsModelI) {
    this.barCode = bar_code;
    this.categoriesId = categories_id;
    this.createdAt = created_at;
    this.depth = depth;
    this.description = description;
    this.fragile = fragile;
    this.heavy = heavy;
    this.height = height;
    this.name = name;
    this.productsId = products_id;
    this.qrCode = qr_code;
    this.quantity = quantity;
    this.refrigerated = refrigerated;
    this.skuCode = sku_code;
    this.updatedAt = updated_at;
    this.weight = weight;
    this.width = width;
  }
}

export default ProductsModel;
